import os
import sys

try:
    from pyreadline3 import Readline
    rl = Readline()
    rl.parse_and_bind("tab: complete")
except ImportError:
    pass
except Exception:
    pass

def get_target_directory():
    print("1. Использовать текущую папку (где скрипт)")
    print("2. Указать путь вручную")
    choice = input("Выбор (1/2): ").strip()

    if choice == '1':
        return os.path.dirname(os.path.abspath(__file__))
    
    print("Введите путь (можно использовать Tab, если установлен pyreadline3):")
    path = input("Путь: ").strip().strip('"').strip("'")
    
    if not os.path.exists(path):
        print(f"Ошибка: Путь '{path}' не найден.")
        sys.exit(1)
    return path

def generate_tree(target_dir):
    root_name = os.path.basename(os.path.abspath(target_dir)) or target_dir
    out = ['Generated by Dov1ntc V1\n', f'{root_name}/']

    def _recurse(prefix, directory):
        try:
            entries = sorted(
                os.listdir(directory),
                key=lambda x: (not os.path.isdir(os.path.join(directory, x)), x.lower())
            )
        except PermissionError:
            return

        filtered_entries = [
            n for n in entries
            if not n.startswith('.') and n not in ('bin', 'obj', '.git')
        ]

        for i, name in enumerate(filtered_entries):
            is_last = i == len(filtered_entries) - 1
            path = os.path.join(directory, name)
            is_dir = os.path.isdir(path)
            
            connector = '└── ' if is_last else '├── '
            suffix = '/' if is_dir else ''
            out.append(f"{prefix}{connector}{name}{suffix}")

            if is_dir:
                extension = '    ' if is_last else '│   '
                _recurse(prefix + extension, path)

    _recurse('', target_dir)
    return '\n'.join(out)

if __name__ == '__main__':
    scan_dir = get_target_directory()
    tree_content = generate_tree(scan_dir)
    print("\nКуда сохранить tree.txt?")
    print("1. В папку, которую сканировали")
    print("2. В папку со скриптом")
    save_choice = input("Выбор (1/2): ").strip()
    
    script_dir = os.path.dirname(os.path.abspath(__file__))
    
    if save_choice == '1':
        save_path = os.path.join(scan_dir, 'tree.txt')
    else:
        save_path = os.path.join(script_dir, 'tree.txt')
        
    with open(save_path, 'w', encoding='utf-8') as f:
        f.write(tree_content)
        
    print(f"Готово. Файл сохранен: {save_path}")